version: '3'

services:
  
#### API GATEWAY ####

  mkt-gateway-api:
    build:
     context: ./Gateways/Mkt.Gateway.API
     #image: buenotales/mkt-gateway-api
    hostname: mkt-gateway-api
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5000:5000"
    networks:
      - mkt-net

#### DATABASES ####

  mkt-domain-product-db-mysql:
    image: mysql
    hostname: mkt-domain-product-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Infrastructure/Mysql/data:/var/lib/mysql
    ports:
      - "5306:3306"
    networks:
      - mkt-net

#### SERVICES OF DOMAINS ####
  
  mkt-domain-product-api:
    build:
     #image: buenotales/mkt-domain-product-api
     context: ./Domains/Product/
    hostname: mkt-domain-product-api
    environment:
      ASPNETCORE_URLS: http://+:5010
      ConnectionStrings__mkt-domain-product-db-mysql: server=mkt-domain-product-db-mysql;port=3306;user=root;password=root;database=mkt-domain-product;
    networks:
      - mkt-net
    depends_on:
      - mkt-domain-product-db-mysql
  
  mkt-domain-order-api:
    build:
     context: ./Domains/Order/
     #image: buenotales/mkt-domain-order-api
    hostname: mkt-domain-order-api
    environment:
      ASPNETCORE_URLS: http://+:5011
    networks:
      - mkt-net

#### SERVICES OF BUSINESS ####
  
  mkt-business-order_submitted-api:
    build:
     context: ./Business/OrderSubmitted/
     #image: buenotales/mkt-business-order_submitted-api
    hostname: mkt-business-order_submitted-api
    environment:
      ASPNETCORE_URLS: http://+:5012
      Order__UrlBase: http://mkt-domain-order-api:5011
      Kafka__Server: mkt-infra-kafka:19091
    networks:
      - mkt-net
    depends_on:
     - mkt-domain-order-api
     - mkt-infra-kafka

  mkt-business-clear_sale_integration-worker:
    build:
     context: ./Business/ClearSaleIntegration/
     #image: buenotales/mkt-business-clear_sale_integration-worker
    hostname: mkt-business-clear_sale_integration-worker
    environment:
      Kafka__Server: mkt-infra-kafka:19091
    networks:
      - mkt-net
    depends_on:
     - mkt-infra-kafka

#### INFRASTUCTURE ####

  mkt-infra-zookeeper:
    image: zookeeper:3.4.9
    hostname: mkt-infra-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=mkt-infra-zookeeper:2888:3888
    volumes:
      - ./Infrastructure/Kafka/data/mkt-infra-zookeeper/data:/data
      - ./Infrastructure/Kafka/data/mkt-infra-zookeeper/datalog:/datalog
    networks:
      - mkt-net

  mkt-infra-kafka:
    image: confluentinc/cp-kafka:5.3.0
    hostname: mkt-infra-kafka
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://mkt-infra-kafka:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "mkt-infra-zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./Infrastructure/Kafka/data/mkt-infra-kafka/data:/var/lib/kafka/data
    depends_on:
      - mkt-infra-zookeeper    
    networks:
      - mkt-net

  mkt-infra-kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "mkt-infra-kafka:19091"
    depends_on:
      - mkt-infra-kafka
    networks:
      - mkt-net

#### NETWORKS ####

networks:
  mkt-net:
    driver: bridge