apiVersion: v1
kind: Service
metadata:
  name: svc-domain-order-api
  namespace: marketplace
  labels:
    app: svc-domain-order-api
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 35011
    targetPort: 5011
    port: 5011
    protocol: TCP
  selector:
    app: pod-domain-order-api 
