apiVersion: v1
kind: Service
metadata:
  name: svc-domain-profile-api
  namespace: marketplace
  labels:
    app: svc-domain-profile-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 5012
    port: 5012
    protocol: TCP
  selector:
    app: pod-domain-profile-api 
