apiVersion: v1
kind: Service
metadata:
  name: svc-gateway-api
  namespace: marketplace
  labels:
    app: svc-gateway-api
spec:
  type: NodePort
  ports:
    targetPort: 5000
    nodePort: 30000
    port: 5000
  selector:
    app: pod-gateway-api